# SPDX-FileCopyrightText: 2026 Bonial International GmbH
# SPDX-License-Identifier: Apache-2.0
---
version: "2"
linters:
  enable:
    - gocritic
    - misspell
    - revive
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters: [revive]
        text: "var-naming: avoid meaningless package names"
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
