# SPDX-FileCopyrightText: 2026 Bonial International GmbH
# SPDX-License-Identifier: Apache-2.0

version: 2

builds:
  - binary: vuln-prio
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - >-
        -s -w
        -X github.com/bonial-oss/trivy-plugin-vuln-prio/cmd.Version={{.Version}}

archives:
  - format: tar.gz
    name_template: "vuln-prio_{{ .Version }}_{{ .Os }}-{{ .Arch }}"

release:
  mode: keep-existing
