# SPDX-FileCopyrightText: 2026 Bonial International GmbH
# SPDX-License-Identifier: Apache-2.0
---
DISABLE:
  - COPYPASTE
  - HTML
  - SPELL

DISABLE_LINTERS:
  - GO_REVIVE # Already running revive via golangci-lint.

EXCLUDED_DIRECTORIES: ["testdata"]
